// Generated by js_of_ocaml 2.6
(function(Z){"use strict";var
H="Sys_error",Q="Invalid_argument",o=1024,P="End_of_file",O="Failure",G="Undefined_recursive_module",N="Stack_overflow",k=128,d="",v=" : file already exists",a=248,M="Not_found",E="Assert_failure",F="/",K="Sys_blocked_io",L="fd ",D="Out_of_memory",J="Match_failure",I="Division_by_zero";function
ax(a,b){var
e=a.length,d=new
Array(e+1),c=0;for(;c<e;c++)d[c]=a[c];d[c]=b;return d}function
A(a,b,c){var
e=new
Array(c);for(var
d=0;d<c;d++)e[d]=a[b+d];return e}function
l(c,b){if(c.fun)return l(c.fun,b);var
a=c.length,d=b.length,e=a-d;if(e==0)return c.apply(null,b);else
if(e<0)return l(c.apply(null,A(b,0,a)),A(b,a,d-a));else
return function(a){return l(c,ax(b,a))}}function
ay(a){var
d=a.length,c=new
Array(d);for(var
b=0;b<d;b++)c[b]=a[b];return c}function
T(a){return function(){return arguments.length>0?l(a,ay(arguments)):l(a,[undefined])}}function
am(a,b){throw[0,a,b]}function
ap(a,b){if(b.repeat)return b.repeat(a);var
c=d,e=0;if(a==0)return c;for(;;){if(a&1)c+=b;a>>=1;if(a==0)return c;b+=b;e++;if(e==9)b.slice(0,1)}}function
z(a,b,c){var
e=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return e.apply(null,a);var
f=d;for(;0<c;b+=o,c-=o)f+=e.apply(null,A(a,b,Math.min(c,o)));return f}function
ae(a){if(a.t==2)a.c+=ap(a.l-a.c.length,"\0");else
a.c=z(a.c,0,a.c.length);a.t=0}function
ah(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
au(a){for(var
l=d,e=d,h,g,i,b,c=0,j=a.length;c<j;c++){g=a.charCodeAt(c);if(g<k){for(var
f=c+1;f<j&&(g=a.charCodeAt(f))<k;f++);if(f-c>512){e.substr(0,1);l+=e;e=d;l+=a.slice(c,f)}else
e+=a.slice(c,f);if(f==j)break;c=f}b=1;if(++c<j&&((i=a.charCodeAt(c))&-64)==k){h=i+(g<<6);if(g<224){b=h-12416;if(b<k)b=1}else{b=2;if(++c<j&&((i=a.charCodeAt(c))&-64)==k){h=i+(h<<6);if(g<240){b=h-925824;if(b<2048||b>=55295&&b<57344)b=2}else{b=3;if(++c<j&&((i=a.charCodeAt(c))&-64)==k&&g<245){b=i-63447168+(h<<6);if(b<65536||b>1114111)b=3}}}}}if(b<4){c-=b;e+="\ufffd"}else
if(b>65535)e+=String.fromCharCode(55232+(b>>10),56320+(b&1023));else
e+=String.fromCharCode(b);if(e.length>o){e.substr(0,1);l+=e;e=d}}return l+e}function
at(a){switch(a.t){case
9:return a.c;default:ae(a);case
0:if(ah(a.c)){a.t=9;return a.c}a.t=8;case
8:return au(a.c)}}function
i(a,b,c){this.t=a;this.c=b;this.l=c}i.prototype.toString=function(){return at(this)};function
c(a){return new
i(0,a,a.length)}function
X(a,b){am(a,c(b))}var
e=[0];function
f(a){X(e.Sys_error,a)}function
y(a){if(!a.opened)f("Cannot flush a closed channel");if(a.buffer==d)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=d;return 0}function
S(a){X(e.Invalid_argument,a)}function
j(a){if(a<0)S("String.create");return new
i(a?2:9,d,a)}var
Y=0;function
az(){return new
Date().getTime()/1e3}function
B(){return Math.floor(az())}function
g(a){this.data=a;this.inode=Y++;var
b=B();this.atime=b;this.mtime=b;this.ctime=b}g.prototype={truncate:function(){this.data=j(0);this.modified()},modified:function(){var
a=B();this.atime=a;this.mtime=a}};function
m(a){return a.l}function
W(a){a=a
instanceof
i?a.toString():a;f(a+": No such file or directory")}var
af=F;function
p(a){a=a
instanceof
i?a.toString():a;if(a.charCodeAt(0)!=47)a=af+a;var
e=a.split(F),b=[];for(var
c=0;c<e.length;c++)switch(e[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(d);break;default:b.push(e[c]);break}b.orig=a;return b}function
h(){this.content={};this.inode=Y++;var
a=B();this.atime=a;this.mtime=a;this.ctime=a}h.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
r=new
h();r.mk(d,new
h());function
x(a){var
b=r;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))W(a.orig);b=b.get(a[c])}return b}function
as(a){var
c=p(a),b=x(c);return b
instanceof
h?1:0}function
aq(a){return new
i(4,a,a.length)}function
R(a){var
c=new
Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
aA(a){if(a.t!=4)R(a);return a.c}function
ag(a,b){var
j=p(a),d=r;for(var
k=0;k<j.length-1;k++){var
e=j[k];if(!d.exists(e))d.mk(e,new
h());d=d.get(e);if(!(d
instanceof
h))f(j.orig+v)}var
e=j[j.length-1];if(d.exists(e))f(j.orig+v);if(b
instanceof
h)d.mk(e,b);else
if(b
instanceof
g)d.mk(e,b);else
if(b
instanceof
i)d.mk(e,new
g(b));else
if(b
instanceof
Array)d.mk(e,new
g(aq(b)));else
if(b.toString)d.mk(e,new
g(c(b.toString())));else
S("caml_fs_register");return 0}function
ar(a){var
b=r,d=p(a),e,f;for(var
c=0;c<d.length;c++){if(b.auto){e=b.auto;f=c}if(!(b.exists&&b.exists(d[c])))return e?e(d,f):0;b=b.get(d[c])}return 1}function
n(a,b,c){if(e.fds===undefined)e.fds=new
Array();c=c?c:{};var
d={};d.file=b;d.offset=c.append?m(b.data):0;d.flags=c;e.fds[a]=d;e.fd_last_idx=a;return a}function
aB(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
h=a.toString(),k=p(a);if(d.rdonly&&d.wronly)f(h+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)f(h+" : flags Open_text and Open_binary are not compatible");if(ar(a)){if(as(a))f(h+" : is a directory");if(d.create&&d.excl)f(h+v);var
i=e.fd_last_idx?e.fd_last_idx:0,g=x(k);if(d.truncate)g.truncate();return n(i+1,g,d)}else
if(d.create){var
i=e.fd_last_idx?e.fd_last_idx:0;ag(a,j(0));var
g=x(k);return n(i+1,g,d)}else
W(a)}n(0,new
g(j(0)));n(1,new
g(j(0)));n(2,new
g(j(0)));function
ai(a){var
b=e.fds[a];if(b.flags.wronly)f(L+a+" is writeonly");return{file:b.file,offset:b.offset,fd:a,opened:true,refill:null}}function
w(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?z(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else
if(c.t==2&&d==c.c.length){c.c+=a.t==4?z(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)R(c);var
g=a.c,h=c.c;if(a.t==4)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
av(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=Z.console;b&&b.error&&b.error(a)}function
aw(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=Z.console;b&&b.log&&b.log(a)}var
q=new
Array();function
ao(a,b){var
h=c(b),d=m(h),g=m(a.file.data),f=a.offset;if(f+d>=g){var
e=j(f+d);w(a.file.data,0,e,0,g);w(h,0,e,f,d);a.file.data=e}a.offset+=d;a.file.modified();return 0}function
U(a){var
b;switch(a){case
1:b=aw;break;case
2:b=av;break;default:b=ao}var
g=e.fds[a];if(g.flags.rdonly)f(L+a+" is readonly");var
c={file:g.file,offset:g.offset,fd:a,opened:true,buffer:d,output:b};q[c.fd]=c;return c}function
aj(){var
a=0;for(var
b
in
q)if(q[b].opened)a=[0,q[b],a];return a}function
V(a,b,c,d){if(!a.opened)f("Cannot output to a closed channel");var
g;if(c==0&&m(b)==d)g=b;else{g=j(d);w(b,c,g,0,d)}var
e=g.toString(),h=e.lastIndexOf("\n");if(h<0)a.buffer+=e;else{a.buffer+=e.substr(0,h+1);y(a);a.buffer+=e.substr(h+1)}return 0}function
ak(a,b){var
d=c(String.fromCharCode(b));V(a,d,0,1);return 0}function
b(a,b,c){e[a+1]=b;if(c)e[c]=b}var
al=0;function
an(a){a[2]=al++;return a}b(11,[a,c(G),-12],G);b(10,[a,c(E),-11],E);b(9,[a,c(K),-10],K);b(8,[a,c(N),-9],N);b(7,[a,c(J),-8],J);b(6,[a,c(M),-7],M);b(5,[a,c(I),-6],I);b(4,[a,c(P),-5],P);b(3,[a,c(Q),-4],Q);b(2,[a,c(O),-3],O);b(1,[a,c(H),-2],H);b(0,[a,c(D),-1],D);an([a,c("Pervasives.Exit"),0]);ai(0);var
s=U(1);U(2);var
ad=c("started server"),ab=c("Handled request"),$=c("All Requires passed");function
t(a){V(s,a,0,m(a));ak(s,10);return y(s)}function
u(a){return require(a)}function
C(a){return u("http")}C(0);u("net");u("url");t($);var
aa=C(0),ac=aa.createServer(T(function(a,b){return t(ab)}));ac.listen(8080,T(function(a){return t(ad)}));function
_(a){var
b=a;for(;;){if(b){var
c=b[2],d=b[1];try{y(d)}catch(f){}var
b=c;continue}return 0}}_(aj(0));return}(function(){return this}()));
