(* let () = *)
(*   Nodejs.Dns.dns##resolve4 *)
(*     (Js.string "google.com") *)
(*     (Js.wrap_callback *)
(*        (fun arr -> *)
(*           Firebug.console##log arr; *)
(*           arr *)
(*           |> Js.str_array |> Js.to_array *)
(*           |> Array.map Js.to_string |> Array.to_list *)
(* |> List.iter print_endline)) *)
